# Generated by Django 5.2.7 on 2026-02-03 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemareservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaevento',
            name='descricao',
        ),
    ]
