# Generated by Django 5.2.7 on 2026-02-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemareservas', '0002_remove_categoriaevento_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaevento',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
